vegetables = ['potato','tomato','cabbage','capsicum','green peas','carrot','cucumber','brinjal','cauliflower','Radish','ladyfinger','onion','beetroot']
print(vegetables,'\n')
# vegetables.append('zoro')
# print(vegetables,'\n')
# vegetables.insert(2,'sasuke')
# print(vegetables,'\n')
# vegetables.remove('Radish')
# print(vegetables,'\n')
# vegetables.pop(6)
# print(vegetables,'\n')
# vegetables.sort()
# print(vegetables,'\n')
# vegetables.reverse()
# print(vegetables,'\n')
# print(len(vegetables),'\n')
# print(vegetables.index('zoro'),'\n')
# print(vegetables.count('zoro'),'\n')
# print(vegetables[-3])
# print(vegetables[3:6],'\n')
# print(vegetables[:6],'\n')
# print(vegetables[-6:])
vegetables.pop()
print(vegetables)